export {default as Profile} from './Profile'
export {default as Menu} from './Menu'
export {default as Hi} from './Hi'
export {default as Resume} from './Resume'
export {default as Contact} from './Contact'
